### ISSUE TITLE
Neither installation from launchpad nor build working

### ISSUE THREAD

**Issue by codesoap** [swami/swami#7]
I want to try `swami` out, but I fail to get it installed. I'm using Xubuntu 18.04.

I first tried installing from the launchpad ppa (as suggested on http://www.swamiproject.org/documentation/installation/), but that didn't work (it seems like the last builds there are from 2010):

```shell
$ sudo add-apt-repository ppa:jgreen-users/element
 Packages for Swami and other related projects.
 More info: https://launchpad.net/~jgreen-users/+archive/ubuntu/element
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Ign:1 http://ppa.launchpad.net/jgreen-users/element/ubuntu bionic InRelease
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [88,7 kB]
Hit:3 http://de.archive.ubuntu.com/ubuntu bionic InRelease
Err:4 http://ppa.launchpad.net/jgreen-users/element/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Hit:5 http://de.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:6 http://de.archive.ubuntu.com/ubuntu bionic-backports InRelease
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/jgreen-users/element/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled
by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Then I tried following the instructions in the `INSTALL` file, but this didn't work either:

```shell
$ ./autogen.sh
automake version: 1.15.1 (ok)
autoconf version: 2.69 (ok)
libtool version: 2.4.6 (ok)
pkg-config: /usr/bin/pkg-config
pkg-config version: 0.29.1 (ok)
generating build system..libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
...configure.ac:20: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
configure.ac:20: http://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
configure.ac:28: installing './compile'
configure.ac:20: installing './missing'
src/libswami/Makefile.am: installing './depcomp'
src/swamigui/Makefile.am:14: error: PYTHON_SUPPORT does not appear in AM_CONDITIONAL
src/swamigui/Makefile.am:82: warning: source file 'widgets/combo-box.c' is in a subdirectory,
src/swamigui/Makefile.am:82: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
src/swamigui/Makefile.am:82: warning: source file 'widgets/icon-combo.c' is in a subdirectory,
src/swamigui/Makefile.am:82: but option 'subdir-objects' is disabled

$ ./configure
-bash: ./configure: No such file or directory
```

What operating systems and way of installation are you using?

**Comment by derselbst** [comment]
We've just started to get things working again. In any case, the autotools build system will be removed sooner or later. You might try using cmake instead.

**Comment by codesoap** [comment]
I tried building with `cmake`, but failed to gather all dependencies for `libinstpatch`.

I wasn't aware that you are in the process of making this project work again right now. Props for that! I'm going to keep an eye on the repo and try installation again in the future.

**Comment by derselbst** [comment]
> I tried building with cmake, but failed to gather all dependencies for libinstpatch.

You must use [libinstpatch](https://github.com/swami/libinstpatch) from recent git or wait for a stable release (which will take some more time).

**Comment by codesoap** [comment]
I had tried building `libinstpatch` from the git repo, but failed there:
```shell
~/Downloads/libinstpatch$ cmake .
-- Checking whether system has ANSI C header files
-- ANSI C header files - found
-- Checking for module 'gobject-introspection-1.0'
--   No package 'gobject-introspection-1.0' found
Build options:
Debug:                 no
GObjectIntrospection:  no
Gtk-Doc API reference: no
-- Configuring done
-- Generating done
-- Build files have been written to: /home/main/Downloads/libinstpatch
```

I have the package `gobject-introspection` (version 1.56.1-1) installed, so I don't understand the problem.

I can wait for the next release. I don't urgently need `swami`, I just want to play around with it some time :-)

**Comment by derselbst** [comment]
It says:

```
-- Configuring done
-- Generating done
```

Which means, it was successful, there is no failure. Just type `make`. You don't need `gobject-introspection`. Just in case you really want it: You need to install the developer package, e.g. `gobject-introspection-devel`.

**Comment by codesoap** [comment]
Ok, thanks for clearing this up.

So I did this in the `libinstpatch` directory:
- `cmake .`
- `make`
- `sudo make install`

I think everything worked so far, but when I now change to the `swami` directory and execute `cmake .` I still get this:

```shell
~/Downloads/swami$ cmake .
-- Checking whether system has ANSI C header files
-- ANSI C header files - found
-- Checking for module 'libinstpatch>=1.1'
--   No package 'libinstpatch' found
CMake Error at /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  CMakeLists.txt:125 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/home/main/Downloads/swami/CMakeFiles/CMakeOutput.log".
```

**Comment by derselbst** [comment]
Please post the output of 
```
pkg-config --list-all  | grep  libinstpatch
pkg-config --modversion libinstpatch
```

I suppose it won't find libinstpatch. Where did you install it? Pls. post the `make install` output.

**Comment by codesoap** [comment]
As you guessed, libinstpatch isn't there:
```shell
~$ pkg-config --list-all  | grep  libinstpatch
~$ pkg-config --modversion libinstpatch
Package libinstpatch was not found in the pkg-config search path.
Perhaps you should add the directory containing `libinstpatch.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libinstpatch' found
```

Here is the output of `sudo make install` for libinstpatch: 
[libinstpatch_make_install.txt](https://github.com/swami/swami/files/3211420/libinstpatch_make_install.txt)

**Comment by derselbst** [comment]
`libinstpatch.pc` was installed to `/usr/local/lib64/pkgconfig/`. pkgconfig doesn't search there by default. Either build libinstpatch again and install into `/usr` (usually you build in a separate directory):

```
cd libinstpatch/
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr ..
make 
sudo make install
```

Or, tell pkgconfig to look in local/

`export PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig`

and build swami again.

**Comment by codesoap** [comment]
Thanks for all your help!

I installed libinstpatch to `/usr`, and `cmake .` now works for swami!

However I'm now stuck at `make`:

```shell
:~/Downloads/swami$ make
[  1%] Linking C shared library libswami.so
/usr/bin/ld: cannot find -llibinstpatch
/usr/bin/ld: cannot find -llibinstpatch
collect2: error: ld returned 1 exit status
src/libswami/CMakeFiles/libswami.dir/build.make:779: recipe for target 'src/libswami/libswami.so.0.0.0' failed
make[2]: *** [src/libswami/libswami.so.0.0.0] Error 1
CMakeFiles/Makefile2:174: recipe for target 'src/libswami/CMakeFiles/libswami.dir/all' failed
make[1]: *** [src/libswami/CMakeFiles/libswami.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by derselbst** [comment]
Oh, my bad. I've fixed that issue locally and haven't pushed it yet. Pls. fetch and install libinstpatch again, should work now.

**Comment by codesoap** [comment]
I did `git pull` for swami and libinstpatch and rebuilt libinstpatch. I still get the same error. I must be doing something wrong...

On a side note: Although I installed fluidsynth, `cmake .` for swami shows me `FluidSynth:            no (there will be no sound!)`. Do I have to configure something to build with fluidsynth support?

**Comment by derselbst** [comment]
> I still get the same error. I must be doing something wrong...

Open `/usr/lib64/pkgconfig/libinstpatch.pc` and make sure it contains `-linstpatch`. If it contains `-llibinstpatch` instead, you've probably installed into `/usr/local/` again. If it does contain `-linstpatch` you have to delete the swami build dir and start over again. And since you did not build in a separate directory, you have to delete the whole swami folder.

> Although I installed fluidsynth, cmake . for swami shows me FluidSynth: no (there will be no sound!).

Make sure you've installed the fluidsynth-devel package. In case you've built it yourself, same procedure as before:
```
pkg-config --list-all  | grep  fluidsynth
pkg-config --modversion fluidsynth
```
If not found, make sure you've installed it to `/usr`.

**Comment by codesoap** [comment]
Alright, it seems like I finally was able to build swami!

Unfortunately I can still not run it. When I enter `swami` in my terminal I get:
```
swami: error while loading shared libraries: libswamigui.so.0: cannot open shared object file: No such file or directory
```

I found the file here, though: `/usr/lib64/libswamigui.so.0`

**Comment by derselbst** [comment]
It should look like this: 

```
ls -la /usr/lib64/libswamigui.so*                                           
lrwxrwxrwx 1 root root     16 18. Mai 10:19 /usr/lib64/libswamigui.so -> libswamigui.so.0                         
lrwxrwxrwx 1 root root     20 18. Mai 10:19 /usr/lib64/libswamigui.so.0 -> libswamigui.so.0.0.0                   
-rwxr-xr-x 1 root root 545896 18. Mai 10:17 /usr/lib64/libswamigui.so.0.0.0
```
Try updating the linker cache: `sudo ldconfig`

**Comment by codesoap** [comment]
I found this:
```shell
$ ls -la /usr/lib64/libswamigui.so*
lrwxrwxrwx 1 root root     16 Mai 23 23:05 /usr/lib64/libswamigui.so -> libswamigui.so.0
lrwxrwxrwx 1 root root     20 Mai 23 23:05 /usr/lib64/libswamigui.so.0 -> libswamigui.so.0.0.0
-rw-r--r-- 1 root root 540456 Mai 23 23:05 /usr/lib64/libswamigui.so.0.0.0
```

So I did `sudo chmod +x /usr/lib64/libswamigui.so.0.0.0` and `sudo ldconfig`, but this didn't help.

I then noticed that swami and libinstpatch were the only libs in `/usr/lib64`, so I moved them to the other libs with `sudo cp /usr/lib64/lib* /usr/lib/x86_64-linux-gnu/`. Now I can start swami and seem to have a functioning GUI 🎉

Thanks for all your support!

**Comment by derselbst** [comment]
Interesting that /usr/lib64/ is not in the linker search path. 

@codesoap Which linux distribution are you using, pls.?

**Comment by codesoap** [comment]
Xubuntu 18.04
